comment: false
coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 0%
        only_pulls: false
        branches: null
        flags: null
        paths: null
  
    

